travis:
  secure:
    BINSTAR_TOKEN: Sile4njSE84/tlpYBFIcb62cHsR7xhMctUZAVlJp9pDvN6wGtqrMkTg/liUQUNLENtjdxpXMDSFBNnOsO17UUAAjEji+ijnb7rIDojGsuJwr5oyeRCi4YbCLT8al3JxQQtQBIv3cgr4g7QypBttGYR0Iq6Mc11Ab53UjHtFVEtSx8Eon0PDdJtFRhWsXjK5ov2x/4IqiWK8ERZge9bdmZ6dc8eVZCCEBQTAaCemKRgFmVCkYPDw2mUlgC6KgfVsDl2JP3wZXZl4/63RnGKOhB5e2zULQxY97Xq5pDq9GHmU3vkuEwfTwBrOC6guioPMn2Zw8DR7f6gvAcU+7Ffzl8TLWbywMbHBuErnXXZxAGNEmzvPNBB1deN85q5+/TrwYGc0u38Q3oFp/KLqfImSLM6Wi2PEIxlLr4B7QtkC8IzQMemGbCNeMzqNLepWlIHYqHyvKMAmj7JUI8j89jfUSS9r+y48pgfxQvh7KQF6uMjN86PPrjvS9sfu9rbaE2AT6pff/CxScl75K7KgPaJbM47F+/zdU4iDI4nQ2i5j0L/rs48tviUGuUrFC+pExI0pDmK9tcinPplfkUML/8q2Bo/T8BqiaG0S4uTC0dCbGwQxyVLJVz4Yf2r40sXVHX2SprUjkimV08HKu6xBTbhx+e4j2Pau7lQyRJraGt+b5MQc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
