travis:
  secure:
    BINSTAR_TOKEN: KKWGnPLqugBkPhQja5Tt2Ek2p66IBN8Oj6VVRY5WYFfHj4mGrRfCPBFQwt0VyWeV44dgBqJWYB7TJBC1FYdIEPt3gcoGX4vTN2CLVM8gOgb6eNOS7daTWi0NL98QkDlbQa8D2QqqGWZUvY1vlt7k5epSyvYQenrwlySBBL1QK6vG29AuJu+5zbsnbJufy7Z2a2Sncvzkf2yz0gV5qQO1oA9EVQ7ikhIXm/B3q7ZRt46xPtkiCvLNpSoPV+W8vuxKTay3pW47vpgXMdctuMss61RcwIXwOkYsjtUE1KEYRfX8iL3AIuaUNgDj6/QLa+uJWKekkiwpO3Ap9SZXtlVGnjAhfOXjHGjZNKzoaHu1KY1Mob824IUnLZqirxGe6QlXRZjKUk+W+VAEGSttVM0AhtrxS4wPA0/ZFAxXkwiCZ9QPwYzOzyUEJvavkneEPU+p2tBVejLukD8lzP0RGJYPTrRjmJ9zwGQmTbEMQzxoydqkGDUTU0C37cxrdFiDfhlxnQUmI2+9EqJcVCTqIUF9FcT6tAlkwqu5eN+OdoiEFpqIy5pprkWtz3m+j6NrIl9JU6kRkQj5/n3yr05zzSny7nPqdoWV935JkYFQSuaeKlFMVZi0yGtajHn1/U2N1JGUxGFxXuo5mZpWDhVkxNcTYFLNOLJNTeQqePggiSgGWPc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
